import { z } from "zod";

/** Opaque content IDs (cases, stages, options). UUIDs from PostgreSQL satisfy this too. */
export const contentIdSchema = z.string().regex(/^[A-Za-z0-9_-]{1,64}$/, "Invalid ID");
export const slugSchema = z
  .string()
  .min(1)
  .max(80)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Invalid slug");
/** Attempt IDs and idempotency keys are always UUIDs generated by the server or the browser's crypto API. */
export const uuidSchema = z.uuid();
